// In-memory data store for demo purposes
// In production this would be replaced by Prisma + PostgreSQL

import { generateHash, generateReceiptNumber, generateWONumber } from "./utils";

// ─── Types ──────────────────────────────────────────────────────────
export interface Company { id: string; name: string; slug: string; plan: string; status: string; createdAt: string; userCount: number; propertyCount: number; }
export interface User { id: string; companyId: string; email: string; name: string; role: string; mfaEnabled: boolean; lastLoginAt: string | null; }
export interface Lead { id: string; companyId: string; name: string; email: string; company: string; stage: string; source: string; pipelineValue: number; propertyCount: number; assignedTo: string; updatedAt: string; }
export interface Proposal { id: string; leadId: string; number: string; status: string; value: number; sentAt: string | null; }
export interface Onboarding { id: string; clientName: string; currentStep: number; totalSteps: number; status: string; propertyCount: number; startedAt: string; }
export interface Asset { id: string; companyId: string; assetCode: string; name: string; type: string; status: string; address: string; acquiredAt: string; purchasePrice: number; currentValue: number; ownerName: string; units: number; occupiedUnits: number; lienStatus: string; legalHolds: boolean; }
export interface Property { id: string; companyId: string; assetId: string; name: string; address: string; type: string; totalUnits: number; status: string; }
export interface Unit { id: string; propertyId: string; unitNumber: string; bedrooms: number; status: string; marketRent: number; }
export interface Tenant { id: string; companyId: string; firstName: string; lastName: string; email: string; phone: string; }
export interface Lease { id: string; unitId: string; unitAddress: string; tenantId: string; tenantName: string; startDate: string; endDate: string; monthlyRent: number; depositAmount: number; status: string; balance: number; latePayments: number; }
export interface WorkOrder { id: string; companyId: string; propertyId: string; propertyAddress: string; woNumber: string; title: string; priority: string; status: string; category: string; vendorName: string; estimatedCost: number; scheduledDate: string | null; createdAt: string; }
export interface CapitalProject { id: string; name: string; budget: number; spent: number; status: string; propertyAddress: string; }
export interface Vendor { id: string; companyId: string; name: string; category: string; status: string; rating: number; }
export interface InsurancePolicy { id: string; companyId: string; assetId: string; carrier: string; policyNumber: string; type: string; coverageAmount: number; premium: number; startDate: string; endDate: string; status: string; }
export interface InsuranceClaim { id: string; policyId: string; claimNumber: string; propertyAddress: string; incidentDate: string; description: string; claimAmount: number; approvedAmount: number | null; status: string; adjusterName: string; }
export interface ComplianceItem { id: string; companyId: string; title: string; propertyAddress: string; category: string; dueDate: string; status: string; assignedTo: string; }
export interface LegalMatter { id: string; companyId: string; type: string; title: string; status: string; hearingDate: string | null; attorney: string; legalHold: boolean; }
export interface Communication { id: string; companyId: string; type: string; toAddress: string; subject: string; status: string; isAutoGenerated: boolean; sentAt: string | null; requiresApproval: boolean; createdAt: string; }
export interface Invoice { id: string; companyId: string; invoiceNumber: string; toName: string; description: string; total: number; dueDate: string; status: string; paidAt: string | null; }
export interface PricingRule { id: string; name: string; type: string; rateType: string; rate: number; description: string; active: boolean; }
export interface TrustAccount { id: string; companyId: string; ownerName: string; balance: number; reserveBalance: number; properties: number; collectedMTD: number; expensesMTD: number; managementFee: number; netDisbursement: number; }
export interface TrustTransaction { id: string; trustAccountId: string; type: string; amount: number; description: string; occurredAt: string; }
export interface WorkflowTemplate { id: string; companyId: string; name: string; trigger: string; steps: number; automations: string[]; active: boolean; }
export interface WorkflowInstance { id: string; templateId: string; templateName: string; entityType: string; entityLabel: string; currentStep: number; totalSteps: number; status: string; startedAt: string; }
export interface Receipt { id: string; companyId: string; receiptNumber: string; type: string; issuedTo: string; eventType: string; eventDescription: string; amount: number | null; hash: string; createdAt: string; }
export interface AuditEngagement { id: string; companyId: string; firmName: string; auditorName: string; scope: string; period: string; status: string; itemsRequested: number; itemsProvided: number; }
export interface AuditDocumentRequest { id: string; engagementId: string; description: string; status: string; }
export interface CloseoutEngagement { id: string; clientName: string; propertyCount: number; status: string; initiatedAt: string; completedAt: string | null; checklistProgress: number; }
export interface AuditLog { id: string; action: string; user: string; company: string; timestamp: string; ipAddress: string; }

// ─── Seed Data ──────────────────────────────────────────────────────────
export const db = {
  companies: [
    { id: "c1", name: "Havilon Realty", slug: "havilon", plan: "enterprise", status: "active", createdAt: "2023-01-15", userCount: 14, propertyCount: 142 },
    { id: "c2", name: "Prestige PM", slug: "prestige", plan: "pro", status: "active", createdAt: "2023-06-01", userCount: 8, propertyCount: 67 },
    { id: "c3", name: "Key West Mgmt", slug: "keywest", plan: "pro", status: "active", createdAt: "2024-02-10", userCount: 6, propertyCount: 34 },
    { id: "c4", name: "Lone Star Props", slug: "lonestar", plan: "starter", status: "trial", createdAt: "2026-05-01", userCount: 2, propertyCount: 8 },
  ] as Company[],

  users: [
    { id: "u1", companyId: "c1", email: "admin@havilon.com", name: "Alex Rivera", role: "admin", mfaEnabled: true, lastLoginAt: "2026-05-30T08:04:00Z" },
    { id: "u2", companyId: "c1", email: "mgr@havilon.com", name: "Jordan Lee", role: "manager", mfaEnabled: true, lastLoginAt: "2026-05-29T14:20:00Z" },
    { id: "u3", companyId: "c1", email: "t.franklin@grantwisecpa.com", name: "T. Franklin", role: "auditor", mfaEnabled: true, lastLoginAt: "2026-05-29T16:11:00Z" },
    { id: "u4", companyId: "c1", email: "m.okafor@state.gov", name: "M. Okafor", role: "auditor", mfaEnabled: false, lastLoginAt: null },
  ] as User[],

  leads: [
    { id: "l1", companyId: "c1", name: "R. Thornton", email: "r.thornton@email.com", company: "Thornton Holdings", stage: "onboarding", source: "Past client", pipelineValue: 1200000, propertyCount: 3, assignedTo: "Jordan Lee", updatedAt: "2026-05-22" },
    { id: "l2", companyId: "c1", name: "L. Kim", email: "l.kim@kimprops.com", company: "Kim Properties LLC", stage: "proposal", source: "Agent referral", pipelineValue: 2100000, propertyCount: 7, assignedTo: "Alex Rivera", updatedAt: "2026-05-28" },
    { id: "l3", companyId: "c1", name: "M. Flores", email: "m.flores@email.com", company: "Individual", stage: "negotiation", source: "Website", pipelineValue: 380000, propertyCount: 1, assignedTo: "Jordan Lee", updatedAt: "2026-05-19" },
    { id: "l4", companyId: "c1", name: "P. Walsh", email: "p.walsh@walshi.com", company: "Walsh Investments", stage: "new", source: "LinkedIn", pipelineValue: 980000, propertyCount: 4, assignedTo: "Alex Rivera", updatedAt: "2026-05-15" },
    { id: "l5", companyId: "c1", name: "A. Chen", email: "a.chen@apexre.com", company: "Apex Real Estate", stage: "new", source: "Past client", pipelineValue: 540000, propertyCount: 2, assignedTo: "Jordan Lee", updatedAt: "2026-05-10" },
  ] as Lead[],

  proposals: [
    { id: "p1", leadId: "l2", number: "P-0044", status: "sent", value: 2100000, sentAt: "2026-05-28" },
    { id: "p2", leadId: "l1", number: "P-0043", status: "accepted", value: 1200000, sentAt: "2026-05-20" },
    { id: "p3", leadId: "l3", number: "P-0042", status: "negotiating", value: 380000, sentAt: "2026-05-18" },
  ] as Proposal[],

  onboardings: [
    { id: "ob1", clientName: "R. Thornton", currentStep: 3, totalSteps: 7, status: "in_progress", propertyCount: 3, startedAt: "2026-05-22" },
    { id: "ob2", clientName: "L. Kim", currentStep: 7, totalSteps: 7, status: "complete", propertyCount: 7, startedAt: "2026-04-10" },
    { id: "ob3", clientName: "S. Patel", currentStep: 7, totalSteps: 7, status: "complete", propertyCount: 2, startedAt: "2026-03-02" },
    { id: "ob4", clientName: "P. Walsh", currentStep: 0, totalSteps: 7, status: "not_started", propertyCount: 4, startedAt: "" },
  ] as Onboarding[],

  assets: [
    { id: "a1", companyId: "c1", assetCode: "AST-00047", name: "220 Oak Ave", type: "multi_family", status: "active", address: "220 Oak Ave, Dallas TX 75201", acquiredAt: "2018-01-15", purchasePrice: 1150000, currentValue: 1420000, ownerName: "L. Kim (Kim Properties LLC)", units: 8, occupiedUnits: 7, lienStatus: "none", legalHolds: false },
    { id: "a2", companyId: "c1", assetCode: "AST-00048", name: "5501 Maple St", type: "single_family", status: "active", address: "5501 Maple St, Dallas TX 75202", acquiredAt: "2020-06-01", purchasePrice: 480000, currentValue: 610000, ownerName: "R. Thornton", units: 1, occupiedUnits: 1, lienStatus: "none", legalHolds: false },
    { id: "a3", companyId: "c1", assetCode: "AST-00049", name: "900 Commerce Blvd", type: "commercial", status: "active", address: "900 Commerce Blvd #12, Dallas TX 75204", acquiredAt: "2019-03-15", purchasePrice: 780000, currentValue: 920000, ownerName: "S. Patel", units: 1, occupiedUnits: 1, lienStatus: "none", legalHolds: true },
  ] as Asset[],

  properties: [
    { id: "pr1", companyId: "c1", assetId: "a1", name: "220 Oak Ave", address: "220 Oak Ave, Dallas TX 75201", type: "multi_family", totalUnits: 8, status: "active" },
    { id: "pr2", companyId: "c1", assetId: "a2", name: "5501 Maple St", address: "5501 Maple St, Dallas TX 75202", type: "single_family", totalUnits: 1, status: "active" },
    { id: "pr3", companyId: "c1", assetId: "a3", name: "900 Commerce Blvd", address: "900 Commerce Blvd, Dallas TX 75204", type: "commercial", totalUnits: 1, status: "active" },
  ] as Property[],

  leases: [
    { id: "le1", unitId: "un1", unitAddress: "220 Oak Ave #4B", tenantId: "t1", tenantName: "M. Torres", startDate: "2024-06-01", endDate: "2027-05-31", monthlyRent: 2200, depositAmount: 2200, status: "active", balance: 0, latePayments: 0 },
    { id: "le2", unitId: "un2", unitAddress: "220 Oak Ave #7A", tenantId: "t2", tenantName: "F. Nguyen", startDate: "2023-07-01", endDate: "2026-06-30", monthlyRent: 2350, depositAmount: 2350, status: "expiring_soon", balance: 0, latePayments: 0 },
    { id: "le3", unitId: "un3", unitAddress: "5501 Maple St", tenantId: "t3", tenantName: "C. Johnson", startDate: "2025-01-01", endDate: "2026-12-31", monthlyRent: 3100, depositAmount: 3100, status: "active", balance: 0, latePayments: 1 },
    { id: "le4", unitId: "un4", unitAddress: "220 Oak Ave #2", tenantId: "", tenantName: "", startDate: "", endDate: "", monthlyRent: 1950, depositAmount: 0, status: "vacant", balance: 0, latePayments: 0 },
    { id: "le5", unitId: "un5", unitAddress: "900 Commerce Blvd #12", tenantId: "t5", tenantName: "TechStart LLC", startDate: "2024-03-01", endDate: "2027-02-28", monthlyRent: 4800, depositAmount: 9600, status: "active", balance: 0, latePayments: 0 },
  ] as Lease[],

  workOrders: [
    { id: "wo1", companyId: "c1", propertyId: "pr2", propertyAddress: "5501 Maple #2", woNumber: "WO-1144", title: "HVAC failure — no cooling", priority: "emergency", status: "in_progress", category: "hvac", vendorName: "CoolAir HVAC", estimatedCost: 3200, scheduledDate: "2026-05-31", createdAt: "2026-05-29" },
    { id: "wo2", companyId: "c1", propertyId: "pr1", propertyAddress: "220 Oak Ave #4B", woNumber: "WO-1138", title: "Plumbing leak under sink", priority: "high", status: "scheduled", category: "plumbing", vendorName: "PlumbRight", estimatedCost: 850, scheduledDate: "2026-06-02", createdAt: "2026-05-27" },
    { id: "wo3", companyId: "c1", propertyId: "pr1", propertyAddress: "220 Oak Ave (common)", woNumber: "WO-1131", title: "Exterior lighting replacement", priority: "low", status: "pending_bid", category: "electrical", vendorName: "", estimatedCost: 320, scheduledDate: null, createdAt: "2026-05-22" },
    { id: "wo4", companyId: "c1", propertyId: "pr3", propertyAddress: "900 Commerce #12", woNumber: "WO-1127", title: "Door lock repair — suite entrance", priority: "high", status: "overdue", category: "general", vendorName: "SecureFix", estimatedCost: 450, scheduledDate: "2026-05-20", createdAt: "2026-05-15" },
  ] as WorkOrder[],

  capitalProjects: [
    { id: "cp1", name: "220 Oak Ave — Roof Replacement", budget: 28000, spent: 28000, status: "complete", propertyAddress: "220 Oak Ave" },
    { id: "cp2", name: "5501 Maple — Kitchen Renovation", budget: 14500, spent: 8700, status: "active", propertyAddress: "5501 Maple St" },
    { id: "cp3", name: "900 Commerce — ADA Ramp Installation", budget: 9200, spent: 1840, status: "active", propertyAddress: "900 Commerce Blvd" },
  ] as CapitalProject[],

  vendors: [
    { id: "v1", companyId: "c1", name: "CoolAir HVAC", category: "hvac", status: "preferred", rating: 4.8 },
    { id: "v2", companyId: "c1", name: "PlumbRight Inc.", category: "plumbing", status: "preferred", rating: 4.7 },
    { id: "v3", companyId: "c1", name: "Apex Roofing", category: "roofing", status: "approved", rating: 4.5 },
    { id: "v4", companyId: "c1", name: "SecureFix Locks", category: "general", status: "approved", rating: 4.2 },
    { id: "v5", companyId: "c1", name: "BrightWorks Electric", category: "electrical", status: "pending", rating: 0 },
  ] as Vendor[],

  insurancePolicies: [
    { id: "ip1", companyId: "c1", assetId: "a1", carrier: "Allstate", policyNumber: "AL-772", type: "property", coverageAmount: 1500000, premium: 4200, startDate: "2025-06-12", endDate: "2026-06-12", status: "active" },
    { id: "ip2", companyId: "c1", assetId: "a2", carrier: "State Farm", policyNumber: "ST-441", type: "property", coverageAmount: 650000, premium: 3800, startDate: "2025-07-01", endDate: "2026-07-01", status: "active" },
    { id: "ip3", companyId: "c1", assetId: "a3", carrier: "Liberty Mutual", policyNumber: "LB-009", type: "commercial", coverageAmount: 1000000, premium: 5100, startDate: "2025-07-22", endDate: "2026-07-22", status: "active" },
  ] as InsurancePolicy[],

  insuranceClaims: [
    { id: "ic1", policyId: "ip1", claimNumber: "CLM-0091", propertyAddress: "220 Oak Ave", incidentDate: "2026-01-10", description: "Roof damage from storm", claimAmount: 12400, approvedAmount: 12400, status: "approved", adjusterName: "B. Harper" },
    { id: "ic2", policyId: "ip2", claimNumber: "CLM-0089", propertyAddress: "5501 Maple St", incidentDate: "2026-04-02", description: "Water intrusion — back wall", claimAmount: 5800, approvedAmount: null, status: "under_review", adjusterName: "D. Chen" },
    { id: "ic3", policyId: "ip3", claimNumber: "CLM-0087", propertyAddress: "900 Commerce #12", incidentDate: "2026-03-18", description: "Vandalism — broken windows", claimAmount: 2100, approvedAmount: null, status: "documentation_needed", adjusterName: "R. Gomez" },
    { id: "ic4", policyId: "ip1", claimNumber: "CLM-0084", propertyAddress: "220 Oak Ave #3A", incidentDate: "2026-01-30", description: "Liability — tenant slip and fall", claimAmount: 0, approvedAmount: null, status: "litigation_hold", adjusterName: "Legal Team" },
  ] as InsuranceClaim[],

  complianceItems: [
    { id: "ci1", companyId: "c1", title: "Fire safety inspection", propertyAddress: "220 Oak Ave", category: "inspection", dueDate: "2026-06-01", status: "overdue", assignedTo: "J. Martinez" },
    { id: "ci2", companyId: "c1", title: "CO detector certification", propertyAddress: "5501 Maple St", category: "certificate", dueDate: "2026-06-03", status: "overdue", assignedTo: "J. Martinez" },
    { id: "ci3", companyId: "c1", title: "Business license renewal", propertyAddress: "Havilon Realty", category: "license", dueDate: "2026-06-30", status: "due_soon", assignedTo: "Admin" },
    { id: "ci4", companyId: "c1", title: "Lead paint disclosure — update", propertyAddress: "900 Commerce #12", category: "disclosure", dueDate: "2026-07-01", status: "upcoming", assignedTo: "S. Patel" },
    { id: "ci5", companyId: "c1", title: "Rent control registration", propertyAddress: "220 Oak Ave", category: "registration", dueDate: "2026-08-15", status: "upcoming", assignedTo: "Admin" },
  ] as ComplianceItem[],

  legalMatters: [
    { id: "lm1", companyId: "c1", type: "litigation", title: "Slip & Fall — 220 Oak #3A", status: "active", hearingDate: "2026-07-14", attorney: "Davis & Lee LLP", plaintiff: "J. Smith", legalHold: true },
    { id: "lm2", companyId: "c1", type: "eviction", title: "Eviction — Unit 2, 220 Oak", status: "in_process", hearingDate: "2026-06-18", attorney: "Internal", plaintiff: "", legalHold: false },
  ] as unknown as LegalMatter[],

  communications: [
    { id: "cm1", companyId: "c1", type: "email", toAddress: "F. Nguyen", subject: "Lease renewal offer — Unit 7A", status: "no_reply", isAutoGenerated: false, sentAt: "2026-04-30", requiresApproval: false, createdAt: "2026-04-30" },
    { id: "cm2", companyId: "c1", type: "sms", toAddress: "C. Johnson", subject: "Maintenance entry notice — Jun 2", status: "delivered", isAutoGenerated: true, sentAt: "2026-05-26", requiresApproval: false, createdAt: "2026-05-26" },
    { id: "cm3", companyId: "c1", type: "email", toAddress: "R. Thornton", subject: "Onboarding step 3 — documents needed", status: "opened", isAutoGenerated: false, sentAt: "2026-05-27", requiresApproval: false, createdAt: "2026-05-27" },
    { id: "cm4", companyId: "c1", type: "email", toAddress: "All Tenants", subject: "June rent reminder", status: "sent", isAutoGenerated: true, sentAt: "2026-05-25", requiresApproval: false, createdAt: "2026-05-25" },
    { id: "cm5", companyId: "c1", type: "notice", toAddress: "Unit 2 Tenant", subject: "Eviction notice — non-payment", status: "draft", isAutoGenerated: false, sentAt: null, requiresApproval: true, createdAt: "2026-05-30" },
    { id: "cm6", companyId: "c1", type: "email", toAddress: "L. Kim", subject: "Owner statement — May 2026", status: "draft", isAutoGenerated: true, sentAt: null, requiresApproval: true, createdAt: "2026-05-30" },
    { id: "cm7", companyId: "c1", type: "email", toAddress: "F. Nguyen", subject: "Renewal follow-up — 2nd reminder", status: "draft", isAutoGenerated: true, sentAt: null, requiresApproval: true, createdAt: "2026-05-30" },
  ] as Communication[],

  invoices: [
    { id: "inv1", companyId: "c1", invoiceNumber: "INV-0841", toName: "L. Kim", description: "Management fee — May 2026", total: 14200, dueDate: "2026-06-01", status: "pending", paidAt: null },
    { id: "inv2", companyId: "c1", invoiceNumber: "INV-0840", toName: "R. Thornton", description: "Onboarding fee", total: 1500, dueDate: "2026-06-01", status: "pending", paidAt: null },
    { id: "inv3", companyId: "c1", invoiceNumber: "INV-0835", toName: "S. Patel", description: "Management fee — May 2026", total: 6400, dueDate: "2026-05-31", status: "paid", paidAt: "2026-05-29" },
    { id: "inv4", companyId: "c1", invoiceNumber: "INV-0829", toName: "P. Walsh", description: "Maintenance markup — April", total: 840, dueDate: "2026-05-15", status: "overdue", paidAt: null },
  ] as Invoice[],

  pricingRules: [
    { id: "pr1", name: "Management Fee", type: "management_fee", rateType: "percentage", rate: 9, description: "8–10% of monthly rent", active: true },
    { id: "pr2", name: "Leasing Fee", type: "leasing_fee", rateType: "percentage", rate: 50, description: "50% of first month's rent", active: true },
    { id: "pr3", name: "Renewal Fee", type: "renewal_fee", rateType: "flat", rate: 250, description: "Flat fee per renewal", active: true },
    { id: "pr4", name: "Maintenance Markup", type: "maintenance_markup", rateType: "percentage", rate: 10, description: "10% on vendor invoices", active: true },
    { id: "pr5", name: "Late Fee", type: "late_fee", rateType: "percentage", rate: 5, description: "5% of rent / $75 minimum", active: true },
  ] as PricingRule[],

  trustAccounts: [
    { id: "ta1", companyId: "c1", ownerName: "L. Kim", balance: 14910, reserveBalance: 42000, properties: 7, collectedMTD: 18900, expensesMTD: 2100, managementFee: 1890, netDisbursement: 14510 },
    { id: "ta2", companyId: "c1", ownerName: "S. Patel", balance: 5130, reserveBalance: 18500, properties: 2, collectedMTD: 6200, expensesMTD: 450, managementFee: 620, netDisbursement: 5130 },
    { id: "ta3", companyId: "c1", ownerName: "R. Thornton", balance: 3685, reserveBalance: 24100, properties: 3, collectedMTD: 7650, expensesMTD: 3200, managementFee: 765, netDisbursement: 3685 },
    { id: "ta4", companyId: "c1", ownerName: "P. Walsh", balance: 9320, reserveBalance: 19800, properties: 4, collectedMTD: 11400, expensesMTD: 940, managementFee: 1140, netDisbursement: 9320 },
  ] as TrustAccount[],

  workflowTemplates: [
    { id: "wt1", companyId: "c1", name: "Client onboarding", trigger: "New contract signed", steps: 7, automations: ["Welcome email", "Receipt", "Task creation"], active: true },
    { id: "wt2", companyId: "c1", name: "Lease renewal", trigger: "90 days before expiry", steps: 5, automations: ["Renewal offer", "Reminders", "Counter-offer"], active: true },
    { id: "wt3", companyId: "c1", name: "Insurance claim", trigger: "Claim filed", steps: 8, automations: ["Adjuster notification", "Doc request", "Follow-up"], active: true },
    { id: "wt4", companyId: "c1", name: "Eviction process", trigger: "Manual trigger", steps: 10, automations: ["Notices", "Court filings", "Legal hold"], active: true },
    { id: "wt5", companyId: "c1", name: "Move-in / move-out", trigger: "Lease start/end", steps: 6, automations: ["Inspection schedule", "Deposit handling"], active: true },
    { id: "wt6", companyId: "c1", name: "Emergency repair", trigger: "WO priority = Emergency", steps: 4, automations: ["Vendor alert", "Owner notification", "Escalation"], active: true },
  ] as WorkflowTemplate[],

  workflowInstances: [
    { id: "wi1", templateId: "wt1", templateName: "Client onboarding", entityType: "onboarding", entityLabel: "R. Thornton", currentStep: 3, totalSteps: 7, status: "active", startedAt: "2026-05-22" },
    { id: "wi2", templateId: "wt2", templateName: "Lease renewal", entityType: "lease", entityLabel: "F. Nguyen — Unit 7A", currentStep: 2, totalSteps: 5, status: "active", startedAt: "2026-04-30" },
    { id: "wi3", templateId: "wt4", templateName: "Eviction process", entityType: "legal", entityLabel: "Unit 2, 220 Oak", currentStep: 3, totalSteps: 10, status: "active", startedAt: "2026-05-03" },
    { id: "wi4", templateId: "wt3", templateName: "Insurance claim", entityType: "claim", entityLabel: "CLM-0089", currentStep: 5, totalSteps: 8, status: "active", startedAt: "2026-04-03" },
  ] as WorkflowInstance[],

  receipts: [
    { id: "r1", companyId: "c1", receiptNumber: "R-2847", type: "lease", issuedTo: "M. Torres", eventType: "Lease renewal executed", eventDescription: "Unit 4B — 3 year renewal signed", amount: null, hash: "a3f9b2c12b", createdAt: "2026-05-28T10:14:22Z" },
    { id: "r2", companyId: "c1", receiptNumber: "R-2846", type: "payment", issuedTo: "L. Kim", eventType: "Rent collection", eventDescription: "May 2026 rent batch — 7 units", amount: 18900, hash: "b7e2441a", createdAt: "2026-05-28T09:01:00Z" },
    { id: "r3", companyId: "c1", receiptNumber: "R-2841", type: "document", issuedTo: "R. Thornton", eventType: "Document upload", eventDescription: "Deed upload — 220 Oak Ave", amount: null, hash: "d1a499ff", createdAt: "2026-05-27T15:22:00Z" },
    { id: "r4", companyId: "c1", receiptNumber: "R-2838", type: "claim", issuedTo: "Allstate", eventType: "Insurance claim submitted", eventDescription: "CLM-0089 — Water intrusion", amount: 5800, hash: "f6c88822", createdAt: "2026-05-26T11:47:00Z" },
    { id: "r5", companyId: "c1", receiptNumber: "R-2830", type: "disbursement", issuedTo: "6 owners", eventType: "Trust disbursement", eventDescription: "May trust disbursement batch", amount: 33155, hash: "aa11cd7e", createdAt: "2026-05-25T14:00:00Z" },
  ] as Receipt[],

  auditEngagements: [
    { id: "ae1", companyId: "c1", firmName: "Grant & Wise CPAs", auditorName: "T. Franklin", scope: "Full portfolio — FY 2025", period: "FY 2025", status: "in_progress", itemsRequested: 10, itemsProvided: 8 },
    { id: "ae2", companyId: "c1", firmName: "State Regulator", auditorName: "M. Okafor", scope: "Trust accounts Q1–Q2 2026", period: "Q1–Q2 2026", status: "pending_docs", itemsRequested: 4, itemsProvided: 3 },
  ] as AuditEngagement[],

  auditDocumentRequests: [
    { id: "adr1", engagementId: "ae1", description: "General ledger (FY25)", status: "provided" },
    { id: "adr2", engagementId: "ae1", description: "Bank statements (12 months)", status: "provided" },
    { id: "adr3", engagementId: "ae1", description: "Trust account reconciliations", status: "provided" },
    { id: "adr4", engagementId: "ae1", description: "All lease agreements", status: "provided" },
    { id: "adr5", engagementId: "ae1", description: "Insurance policies", status: "in_review" },
    { id: "adr6", engagementId: "ae1", description: "Capital expenditure records", status: "pending" },
    { id: "adr7", engagementId: "ae1", description: "Maintenance invoices > $1,000", status: "pending" },
  ] as AuditDocumentRequest[],

  closeouts: [
    { id: "co1", clientName: "J. Anderson", propertyCount: 2, status: "in_progress", initiatedAt: "2026-05-01", completedAt: null, checklistProgress: 67 },
    { id: "co2", clientName: "B. Carter", propertyCount: 1, status: "complete", initiatedAt: "2026-01-15", completedAt: "2026-02-28", checklistProgress: 100 },
    { id: "co3", clientName: "T. Morris", propertyCount: 5, status: "archived", initiatedAt: "2024-11-01", completedAt: "2024-12-15", checklistProgress: 100 },
  ] as CloseoutEngagement[],

  auditLogs: [
    { id: "al1", action: "Login (MFA verified)", user: "admin@havilon.com", company: "Havilon Realty", timestamp: "2026-05-30T08:04:00Z", ipAddress: "104.21.x.x" },
    { id: "al2", action: "Document exported", user: "t.franklin@grantwisecpa.com", company: "Havilon (Auditor)", timestamp: "2026-05-29T16:11:00Z", ipAddress: "172.16.x.x" },
    { id: "al3", action: "Invoice approved", user: "mgr@havilon.com", company: "Havilon Realty", timestamp: "2026-05-29T14:38:00Z", ipAddress: "104.21.x.x" },
    { id: "al4", action: "Failed login (account locked)", user: "unknown@domain.com", company: "—", timestamp: "2026-05-28T23:52:00Z", ipAddress: "195.x.x.x" },
  ] as AuditLog[],
};
