import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { requireRole, writeAuditLog } from "@/auth/session";
import { z } from "zod";

const createCommSchema = z.object({
  type: z.enum(["email","sms","notice","letter"]),
  toAddress: z.string().min(1),
  subject: z.string().optional(),
  body: z.string().min(1),
  relatedEntity: z.string().optional(),
  relatedEntityId: z.string().optional(),
  requiresApproval: z.boolean().default(false),
  sendNow: z.boolean().default(false),
});

export async function GET(request: NextRequest) {
  const ctx = await requireRole(request, ["admin","manager"]);
  if (ctx instanceof NextResponse) return ctx;
  const { searchParams } = new URL(request.url);
  const status = searchParams.get("status");
  const pendingApproval = searchParams.get("pendingApproval");
  const comms = await prisma.communication.findMany({
    where: { companyId: ctx.companyId, ...(status ? { status } : {}), ...(pendingApproval === "true" ? { status: "pending_approval" } : {}) },
    orderBy: { createdAt: "desc" }, take: 50,
  });
  return NextResponse.json({ communications: comms });
}

export async function POST(request: NextRequest) {
  const ctx = await requireRole(request, ["admin","manager"]);
  if (ctx instanceof NextResponse) return ctx;
  const body = await request.json();

  if (body.action === "approve" || body.action === "reject") {
    const comm = await prisma.communication.findFirst({ where: { id: body.commId, companyId: ctx.companyId } });
    if (!comm) return NextResponse.json({ error: "Not found" }, { status: 404 });
    if (body.action === "approve") {
      const updated = await prisma.communication.update({ where: { id: comm.id }, data: { status: "sent", sentAt: new Date(), approvedBy: ctx.userId } });
      await writeAuditLog(ctx.companyId, ctx.userId, "approve_send", "Communication", comm.id);
      return NextResponse.json(updated);
    }
    const updated = await prisma.communication.update({ where: { id: comm.id }, data: { status: "draft" } });
    return NextResponse.json(updated);
  }

  const parsed = createCommSchema.safeParse(body);
  if (!parsed.success) return NextResponse.json({ error: "Validation failed", details: parsed.error.flatten() }, { status: 422 });
  const status = parsed.data.sendNow ? "sent" : parsed.data.requiresApproval ? "pending_approval" : "draft";
  const comm = await prisma.communication.create({
    data: { companyId: ctx.companyId, type: parsed.data.type, direction: "outbound", toAddress: parsed.data.toAddress, subject: parsed.data.subject, body: parsed.data.body, status, isAutoGenerated: false, relatedEntity: parsed.data.relatedEntity, relatedEntityId: parsed.data.relatedEntityId, sentAt: parsed.data.sendNow ? new Date() : undefined },
  });
  await writeAuditLog(ctx.companyId, ctx.userId, "create", "Communication", comm.id, { type: comm.type, status: comm.status });
  return NextResponse.json(comm, { status: 201 });
}
