import { db } from "@/lib/store";
import { formatDateShort } from "@/lib/utils";
import {
  Card, CardHeader, CardTitle, MetricCard, MetricsGrid, PageTopBar,
  SectionPage, TwoCol, Table, Th, Td, Tr, Btn,
} from "@/components/ui";
import { Badge, statusVariant } from "@/components/ui/Badge";
import { Plus, FileText } from "lucide-react";

const templates = [
  "Rent Increase Notice", "Entry Notice (24hr)", "Late Rent Warning",
  "Lease Renewal Offer", "Move-out Instructions", "3-Day Notice to Pay",
];

export default function CommunicationsPage() {
  const pending = db.communications.filter((c) => c.requiresApproval && c.status === "draft");
  const autoSent = db.communications.filter((c) => c.isAutoGenerated && c.sentAt).length;

  return (
    <>
      <PageTopBar title="Communications" subtitle="Email · SMS · Call Logs · Notices · Approvals">
        <Btn variant="primary"><Plus size={13} /> Compose</Btn>
      </PageTopBar>
      <SectionPage>
        <MetricsGrid>
          <MetricCard label="Sent This Month" value={284} />
          <MetricCard label="Pending Approval" value={pending.length} />
          <MetricCard label="Unread Replies" value={12} />
          <MetricCard label="Auto-Sent (AI)" value={autoSent} />
        </MetricsGrid>

        <TwoCol>
          <Card>
            <CardHeader><CardTitle>Recent Communications</CardTitle></CardHeader>
            <Table>
              <thead>
                <tr><Th>To</Th><Th>Type</Th><Th>Subject</Th><Th>Date</Th><Th>Status</Th></tr>
              </thead>
              <tbody>
                {db.communications.filter((c) => c.sentAt).map((comm) => (
                  <Tr key={comm.id}>
                    <Td>{comm.toAddress}</Td>
                    <Td>
                      <Badge variant={comm.type === "email" ? "blue" : comm.type === "sms" ? "purple" : "gray"}>
                        {comm.type}
                      </Badge>
                    </Td>
                    <Td className="max-w-[160px] truncate text-xs">{comm.subject}</Td>
                    <Td>{comm.sentAt ? formatDateShort(comm.sentAt) : "—"}</Td>
                    <Td><Badge variant={statusVariant(comm.status.replace(" ", "_"))}>{comm.status.replace("_", " ")}</Badge></Td>
                  </Tr>
                ))}
              </tbody>
            </Table>
          </Card>

          <Card>
            <CardHeader><CardTitle>Pending Approval ({pending.length})</CardTitle></CardHeader>
            <div className="space-y-3">
              {pending.map((comm) => (
                <div key={comm.id} className="flex justify-between items-start p-3 bg-slate-50 rounded-lg">
                  <div>
                    <div className="text-sm font-semibold text-slate-800">{comm.subject}</div>
                    <div className="text-xs text-slate-500 mt-0.5">
                      {comm.isAutoGenerated ? "AI-drafted" : "Manual"} · {comm.type} · To: {comm.toAddress}
                    </div>
                  </div>
                  <div className="flex gap-1.5 ml-3 flex-shrink-0">
                    <Btn variant="primary">
                      {comm.type === "notice" ? "Approve" : "Send"}
                    </Btn>
                    <Btn>Edit</Btn>
                  </div>
                </div>
              ))}
            </div>
          </Card>
        </TwoCol>

        <Card>
          <CardHeader><CardTitle>Notice Templates</CardTitle></CardHeader>
          <div className="flex flex-wrap gap-2">
            {templates.map((t) => (
              <Btn key={t}>
                <FileText size={12} />
                {t}
              </Btn>
            ))}
          </div>
        </Card>
      </SectionPage>
    </>
  );
}
